/**
 * Generate the committed CLI reference (`docs/cli.md`) from the command
 * registry. Usage strings live next to each command's parseArgs — this is the
 * single source of truth for the agent-facing surface.
 *
 * Regenerate:
 *   pnpm --filter @excalidraw-collab/cli generate-cli-ref
 *
 * Drift is enforced by cli-ref.drift.test.ts.
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { listCommands, CLI_VERSION } from "./commands.js";

/** Path of the committed reference, relative to the monorepo root. */
export const CLI_REF_RELATIVE_PATH = "docs/cli.md";

/** Absolute path to the committed CLI reference for a given monorepo root. */
export function cliRefPath(repoRoot: string): string {
  return path.join(repoRoot, CLI_REF_RELATIVE_PATH);
}

/**
 * Resolve monorepo root from this module's location
 * (`packages/cli/src` or `packages/cli/dist`).
 */
export function resolveMonorepoRoot(
  fromUrl: string | URL = import.meta.url,
): string {
  const dir = path.dirname(fileURLToPath(fromUrl));
  return path.resolve(dir, "../../..");
}

/**
 * Build the full markdown document for `docs/cli.md`.
 * Output is deterministic (sorted command list, stable headers).
 */
export function generateCliReference(): string {
  const cmds = listCommands();
  const lines: string[] = [
    "<!-- Generated by packages/cli — do not edit by hand. -->",
    "<!-- Regenerate: pnpm --filter @excalidraw-collab/cli generate-cli-ref -->",
    "",
    "# excalicli reference",
    "",
    "Auto-generated from the command registry in `packages/cli` (each command's",
    "`name`, `description`, and `usage` string next to its `parseArgs` parser).",
    "Do not edit this file by hand — regenerate and commit when the CLI surface changes.",
    "",
    `CLI package version: \`${CLI_VERSION}\`.`,
    "",
    "## Invocation",
    "",
    "```",
    "excalicli [--json] <command> [options]",
    "```",
    "",
    "Global options apply before or after the command name:",
    "",
    "| Flag | Description |",
    "|---|---|",
    "| `--json` | Emit exactly one JSON value on stdout (errors: one JSON error envelope) |",
    "| `-h`, `--help` | Show help (global command list, or per-command usage) |",
    "",
    "Per-command help: `excalicli <command> --help`.",
    "",
    "Machine-readable command list: `excalicli --json` (no subcommand).",
    "",
    "## Exit codes",
    "",
    "| Code | Name | Meaning |",
    "|---:|---|---|",
    "| 0 | OK | Success (including empty diffs) |",
    "| 1 | ERROR | Runtime / server / I/O failure |",
    "| 2 | USAGE | Bad arguments, missing auth/config, or missing prior pull |",
    "| 4 | CONFLICT | Optimistic-concurrency push rejected (409); diff is in the response |",
    "| 5 | LOCK_HELD | Advisory turn lock held by someone else (`turn claim`, or `push --respect-lock`) |",
    "",
    "## Commands",
    "",
  ];

  for (const c of cmds) {
    lines.push(`### \`${c.name}\``);
    lines.push("");
    lines.push(c.description);
    lines.push("");
    lines.push("```");
    // usage may be multi-line (flags + notes)
    lines.push(c.usage ?? `excalicli ${c.name}`);
    lines.push("```");
    lines.push("");
  }

  // Trailing newline for POSIX text files.
  return lines.join("\n");
}
